enum ResponseStatus {
    STATUSCODE_SUCCESS = '190',
    STATUSCODE_FAILED = '490',
    STATUSCODE_VALIDATION_FAILURE = '491',
    STATUSCODE_TECHNICAL_ERROR = '492',
    STATUSCODE_REJECTED = '690',
    STATUSCODE_WAITING_ON_USER_INPUT = '790',
    STATUSCODE_PENDING_PROCESSING = '791',
    STATUSCODE_WAITING_ON_CONSUMER = '792',
    STATUSCODE_PAYMENT_ON_HOLD = '793',
    STATUSCODE_CANCELLED_BY_USER = '890',
    STATUSCODE_CANCELLED_BY_MERCHANT = '891',
    AUTHORIZE_TYPE_CANCEL = 'I014',
    AUTHORIZE_TYPE_ACCEPT = 'I013',
    AUTHORIZE_TYPE_GROUP_TRANSACTION = 'I150',
}

export default ResponseStatus;
