import afterpay from "../PaymentMethods/Afterpay";
import AfterpayDigiAccept from "../PaymentMethods/AfterpayDigiAccept";
import alipay from "../PaymentMethods/Alipay";
import ApplePay from "../PaymentMethods/ApplePay";
import bancontact from "../PaymentMethods/Bancontact";
import banktransfer from "../PaymentMethods/BankTransfer";
import belfius from "../PaymentMethods/Belfius";
import Billink from "../PaymentMethods/Billink";
import BuckarooVoucher from "../PaymentMethods/BuckarooVoucher";
import creditClick from "../PaymentMethods/CreditClick";
import CreditManagement from "../PaymentMethods/CreditManagement";
import EPS from "../PaymentMethods/EPS";
import giftcard from "../PaymentMethods/GiftCard";
import giropay from "../PaymentMethods/Giropay";
import ideal from "../PaymentMethods/Ideal";
import iDEALQR from "../PaymentMethods/iDealQR";
import in3 from "../PaymentMethods/In3";
import kbc from "../PaymentMethods/KBC";
import klarna from "../PaymentMethods/Klarna";
import payconiq from "../PaymentMethods/Payconiq";
import paypal from "../PaymentMethods/Paypal";
import payperemail from "../PaymentMethods/PayPerEmail";
import przelewy24 from "../PaymentMethods/Przelewy24";
import SEPA from "../PaymentMethods/SEPA";
import sofort from "../PaymentMethods/Sofort";
import Subscriptions from "../PaymentMethods/Subscriptions";
import Surepay from "../PaymentMethods/Surepay";
import Tinka from "../PaymentMethods/Tinka";
import Trustly from "../PaymentMethods/Trustly";
import WeChatPay from "../PaymentMethods/WeChatPay";
export declare class Methods {
    private _afterpay;
    get afterpay(): ReturnType<typeof afterpay>;
    private _afterPayDigiAccept;
    get afterPayDigiAccept(): ReturnType<typeof AfterpayDigiAccept>;
    private _alipay;
    get alipay(): ReturnType<typeof alipay>;
    private _applePay;
    get applePay(): ReturnType<typeof ApplePay>;
    private _bancontact;
    get bancontact(): ReturnType<typeof bancontact>;
    private _banktransfer;
    get banktransfer(): ReturnType<typeof banktransfer>;
    private _belfius;
    get belfius(): ReturnType<typeof belfius>;
    private _billink;
    get billink(): ReturnType<typeof Billink>;
    private _buckarooVoucher;
    get buckarooVoucher(): ReturnType<typeof BuckarooVoucher>;
    private _creditClick;
    get creditClick(): ReturnType<typeof creditClick>;
    private _creditManagement;
    get creditManagement(): ReturnType<typeof CreditManagement>;
    private _eps;
    get eps(): ReturnType<typeof EPS>;
    private _giftcard;
    get giftcard(): ReturnType<typeof giftcard>;
    private _giropay;
    get giropay(): ReturnType<typeof giropay>;
    private _ideal;
    get ideal(): ReturnType<typeof ideal>;
    private _iDEALQR;
    get iDEALQR(): ReturnType<typeof iDEALQR>;
    private _in3;
    get in3(): ReturnType<typeof in3>;
    private _kbc;
    get kbc(): ReturnType<typeof kbc>;
    private _klarna;
    get klarna(): ReturnType<typeof klarna>;
    private _payconiq;
    get payconiq(): ReturnType<typeof payconiq>;
    private _paypal;
    get paypal(): ReturnType<typeof paypal>;
    private _payperemail;
    get payperemail(): ReturnType<typeof payperemail>;
    private _przelewy24;
    get przelewy24(): ReturnType<typeof przelewy24>;
    private _sepa;
    get sepa(): ReturnType<typeof SEPA>;
    private _sofort;
    get sofort(): ReturnType<typeof sofort>;
    private _subscriptions;
    get subscriptions(): ReturnType<typeof Subscriptions>;
    private _surepay;
    get surepay(): ReturnType<typeof Surepay>;
    private _tinka;
    get tinka(): ReturnType<typeof Tinka>;
    private _trustly;
    get trustly(): ReturnType<typeof Trustly>;
    private _wechatPay;
    get wechatPay(): ReturnType<typeof WeChatPay>;
}
